# Note that all relative paths are based on the path of index.php
logging:
  # level = {debug|info|warn|error}
  level: debug
  file: ./log/log.txt
timezone: Asia/Tokyo
default_style: sample-style-1
default_refresh_timetable: forecast

include_dir: ./config/include

# dither_palette
# define palettes to use when dithering the image
# (structure)
#   name-of-the-palette:
#     palette:
#       number = [R, G, B]
#       ...
#     amount = 0..1 : How heavily the dithering effect is to be applied.
dither_palette:
  7color:
    palette:
      0: [  0,   0,   0] # black
      1: [255, 255, 255] # white
      2: [  0, 255,   0] # green
      3: [  0,   0, 255] # blue
      4: [255,   0,   0] # red
      5: [255, 255,   0] # yellow
      6: [255, 170,   0] # orange
    amount: 0.75

# refresh_time
# define timetables to be used when calculating the remaining seconds to the next nearest time in the timetable
# when `mode=timer` is set to this program
# (structure)
#   name-of-the-timetable:
#     - time
#     - ...
refresh_timetable:
  forecast:
    - '0:00'
    - '5:00'
    - '11:00'
    - '17:00'
    - '20:00'

holiday:
  japan-1:
    default_holiday_name: 休日
    substitute_holiday_name: 振替休日
    default_holiday_color: [0, 255, 0, 0]
    holiday_name_separator: '/'
    # holiday_rule_sandwich
    #   true: Activate Article 3, paragraph (3) of National Holiday Act in Japan.
    #   false: Deactivate Article 3, paragraph (3) of National Holiday Act in Japan.
    #   祝日法第3条第3項 その前日及び翌日が「国民の祝日」である日（「国民の祝日」でない日に限る。）は、休日とする。
    holiday_rule_sandwich: true
    # rule_set
    # define holiday rules
    # rule: A date format to represent the holiday. https://www.php.net/manual/en/datetime.formats.php
    #   (Special keyword)
    #    - The word "VED" is replaced to the date of Vernal Equinox Day, usually "3/20" or "3/21"
    #    - The word "AED" is replaced to the date of Autumnal Equinox Day, usually "9/22" or "9/23"
    # name = null | string : Holiday name
    # type = {national_holiday | work_holiday}
    # substitute_when = null | [{sunday | saturday | national_holiday | work_holiday}...] : When to substitute the holiday
    # substitution_avoid = null | [{sunday | saturday | national_holiday | work_holiday}...] : Days to exclude from candidates of the substitute holiday
    # ex. substitute holiday defined in Article 3, paragraph (2) of National Holiday Act in Japan can be expressed as
    #       substitute_when = ["sunday"] and substitution_avoid = ["national_holiday"]
    #     祝日法第3条第2項 「国民の祝日」が日曜日に当たるときは、その日後においてその日に最も近い「国民の祝日」でない日を休日とする。
    rule_set:
      - rule: 1/1
        name: 元日
        type: national_holiday
        color: [255, 0, 0, 0]
        substitute_when: [sunday]
        substitution_avoid: [national_holiday]
      - rule: second monday of January
        name: 成人の日
        type: national_holiday
        color: [255, 0, 0, 0]
        substitute_when: [sunday]
        substitution_avoid: [national_holiday]
      - rule: 2/11
        name: 建国記念の日
        type: national_holiday
        color: [255, 0, 0, 0]
        substitute_when: [sunday]
        substitution_avoid: [national_holiday]
      - rule: 2/23
        name: 天皇誕生日
        type: national_holiday
        color: [255, 0, 0, 0]
        substitute_when: [sunday]
        substitution_avoid: [national_holiday]
      - rule: VED
        name: 春分の日
        type: national_holiday
        color: [255, 0, 0, 0]
        substitute_when: [sunday]
        substitution_avoid: [national_holiday]
      - rule: 4/29
        name: 昭和の日
        type: national_holiday
        color: [255, 0, 0, 0]
        substitute_when: [sunday]
        substitution_avoid: [national_holiday]
      - rule: 5/3
        name: 憲法記念日
        type: national_holiday
        color: [255, 0, 0, 0]
        substitute_when: [sunday]
        substitution_avoid: [national_holiday]
      - rule: 5/4
        name: みどりの日
        type: national_holiday
        color: [255, 0, 0, 0]
        substitute_when: [sunday]
        substitution_avoid: [national_holiday]
      - rule: 5/5
        name: こどもの日
        type: national_holiday
        color: [255, 0, 0, 0]
        substitute_when: [sunday]
        substitution_avoid: [national_holiday]
      - rule: third monday of July
        name: 海の日
        type: national_holiday
        color: [255, 0, 0, 0]
        substitute_when: [sunday]
        substitution_avoid: [national_holiday]
      - rule: 8/11
        name: 山の日
        type: national_holiday
        color: [255, 0, 0, 0]
        substitute_when: [sunday]
        substitution_avoid: [national_holiday]
      - rule: third monday of September
        name: 敬老の日
        type: national_holiday
        color: [255, 0, 0, 0]
        substitute_when: [sunday]
        substitution_avoid: [national_holiday]
      - rule: AED
        name: 秋分の日
        type: national_holiday
        color: [255, 0, 0, 0]
        substitute_when: [sunday]
        substitution_avoid: [national_holiday]
      - rule: second monday of October
        name: スポーツの日
        type: national_holiday
        color: [255, 0, 0, 0]
        substitute_when: [sunday]
        substitution_avoid: [national_holiday]
      - rule: 11/3
        name: 文化の日
        type: national_holiday
        color: [255, 0, 0, 0]
        substitute_when: [sunday]
        substitution_avoid: [national_holiday]
      - rule: 11/23
        name: 勤労感謝の日
        type: national_holiday
        color: [255, 0, 0, 0]
        substitute_when: [sunday]
        substitution_avoid: [national_holiday]
      - rule: 12/29
        name: 年末年始休
        type: work_holiday
        color: [255, 0, 0, 0]
        substitute_when: []
        substitution_avoid: []
      - rule: 12/30
        name: 年末年始休
        type: work_holiday
        color: [255, 0, 0, 0]
        substitute_when: []
        substitution_avoid: []
      - rule: 12/31
        name: 年末年始休
        type: work_holiday
        color: [255, 0, 0, 0]
        substitute_when: []
        substitution_avoid: []
      - rule: 1/2
        name: 年末年始休
        type: work_holiday
        color: [255, 0, 0, 0]
        substitute_when: []
        substitution_avoid: []
      - rule: 1/3
        name: 年末年始休
        type: work_holiday
        color: [255, 0, 0, 0]
        substitute_when: []
        substitution_avoid: []



